### ISSUE TITLE
Use a newer pandoc version in pypandoc-binary (currently 2.19.2)

### ISSUE THREAD

**Issue by hideintheclouds** [JessicaTegner/pypandoc#375]
One of the main use cases of pypandoc-binary is in an airgapped environment, when the user does not have control over the version of pandoc to install.

Currently, the version that comes packed is hardcoded to 2.19.2, which seem to be aprox 2 years old.

It would be beneficial to include the latest version in the package, as not all of the commands supported by pandoc are understood by pypandoc.

https://github.com/JessicaTegner/pypandoc/blob/master/setup_binary.py
 #[pandoc 2.19.2](https://github.com/JessicaTegner/pypandoc/blob/master/setup_binary.py)

https://pandoc.org/releases.html#pandoc-2.19.2-2022-08-22

**Comment by JessicaTegner** [comment]
Ohh dam. Actually didn't notice that the version was hardcoded. THat's not by design.
I've actually been looking into a way of generating a few pypandoc_binary versions every time, with different pandoc versions bundled, but never really could figure out how that would work.

But case and point, yes the version should not be hardcoded.

**Comment by saisatwik-ema** [comment]
@JessicaTegner waiting on this. Can you please merge the PR.
