### ISSUE TITLE
[help] Display live output to console?

### ISSUE THREAD

**Issue by Shohreh** [JessicaTegner/pypandoc#385]
Hello

Searching the archives returned nothing.

Since pandoc can take a while to convert an HTML document to EPUB, I'd like to display progress in the console so the user knows it's not stuck.

Is there a way to do that?

I currently use this:
```
os.environ.setdefault('PYPANDOC_PANDOC', r'c:\pandoc.exe')
extra_args=['--epub-title-page=false','--metadata',f'author={AUTHOR}','--metadata',f'title={TITLE}']
output = pypandoc.convert_text(html_content, format='html',to='epub',outputfile=OUTPUTFILE, extra_args=extra_args)
```

Thank you.

**Comment by JessicaTegner** [comment]
hi @Shohreh 

How long does it normally take for you?

There is no native way of doing it in pandoc as far as I'm awear, and that's why pypandoc doesn't have that functionality either.

One way of doing it yourself, is to use the multiprocessing or threading module yourself, and run the pypandoc.convert_text call in another thread, and then display an indeterminate progress bar or similar while waiting for the thread/process to complete.

Let me know if this is what you are looking for/ if this solves your issue.

**Comment by Shohreh** [comment]
> How long does it normally take for you?

On a big document, it can take long enough that the user might think it's stuck.

I'll look at running a thread, or just print a message before and after to show it worked.

Thank you.
